poc.AspNet.Core.MVC/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace poc.AspNet.Core.MVC.Models
{
    public class LoginViewModel
    {
        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail id is not valid")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

poc.AspNet.Core.MVC/Controllers/ContaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using poc.AspNet.Core.Domain.Interfaces.Services;
using poc.AspNet.Core.Ioc.Entities;
using poc.AspNet.Core.MVC.Models;
using System.Collections.Generic;
using System.Security.Claims;

namespace poc.AspNet.Core.MVC.Controllers
{
    public class ContaController : Controller
    {
        protected readonly IUsuarioService _service;
        protected readonly IEquipeService _serviceEquipe;
        protected readonly IPrevisaoTempoService _servicePrevisaoTempo;
        protected readonly IMapper _mapper;

        public ContaController(
            IUsuarioService service,
            IEquipeService serviceEquipe,
            IPrevisaoTempoService servicePrevisaoTempo,
            IMapper mapper
        )
        {
            _service = service;
            _serviceEquipe = serviceEquipe;
            _mapper = mapper;
            _servicePrevisaoTempo = servicePrevisaoTempo;
        }
        // Return Home page.
        public ActionResult Index()
        {
            if (User.Identity?.Name != null)
            {
                ViewBag.DadosUsuario = _service.BuscarDadosDoUsuario(User.Identity.Name);
                ViewBag.PrevisaoTempo = _mapper.Map<PrevisaoTempoCidade, PrevisaoTempoCidadeViewModel>(_servicePrevisaoTempo.GetPrevisaoPorIp(HttpContext.Connection.RemoteIpAddress.ToString()));
                return View("Logado");
            }


            return View();
        }

        // Return Home page.
        public ActionResult Logado()
        {
            if (User.Identity != null && User.Identity.Name != null && User.Identity.Name != "")
            {
                ViewBag.DadosUsuario = _service.BuscarDadosDoUsuario(User.Identity.Name);
                ViewBag.PrevisaoTempo = _mapper.Map<PrevisaoTempoCidade, PrevisaoTempoCidadeViewModel>(_servicePrevisaoTempo.GetPrevisaoPorIp(HttpContext.Connection.RemoteIpAddress.ToString()));
                return View();
            }


            return View();
        }

        //Return Register view
        public ActionResult Register()
        {
            var equipes = _mapper.Map<IEnumerable<Equipe>, IEnumerable<EquipeViewModel>>(_serviceEquipe.GetAll());
            var model = new UsuarioViewModel
            {
                Equipes = new SelectList(equipes, "Id", "Nome")
            };

            return View(model);
        }

        //The form's data in Register view is posted to this method. 
        //We have binded the Register View with Register ViewModel, so we can accept object of Register class as parameter.
        //This object contains all the values entered in the form by the user.
        [HttpPost]
        public ActionResult Register(UsuarioViewModel usuario)
        {
            //We check if the model state is valid or not. We have used DataAnnotation attributes.
            //If any form value fails the DataAnnotation validation the model state becomes invalid.
            if (ModelState.IsValid)
            {
                //create database context using Entity framework 
                _service.Registrar(_mapper.Map<UsuarioViewModel, Usuario>(usuario));

                ViewBag.Message = "Usuário registrado com sucesso";
                return RedirectToAction("Index");
            }
            else
            {

                //If the validation fails, we are returning the model object with errors to the view, which will display the error messages.
                return View(usuario);
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        //The login form is posted to this method.
        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            //Checking the state of model passed as parameter.
            if (ModelState.IsValid)
            {

                //Validating the user, whether the user is valid or not.
                var isValidUser = IsValidUser(model);

                //If user is valid & present in database, we are redirecting it to Welcome page.
                if (isValidUser != null)
                {
                    var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, model.Email)
                        };
                    var claimsIdentity = new ClaimsIdentity(
                        claims,
                        CookieAuthenticationDefaults.AuthenticationScheme
                    );

                    var authProperties = new AuthenticationProperties { };

                    HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties
                    ).Wait();

                    //FormsAuthentication.SetAuthCookie(model.Email, false);
                    return RedirectToAction("Index", "Conta");
                }
                else
                {
                    //If the username and password combination is not present in DB then error message is shown.
                    ModelState.AddModelError("Failure", "Wrong Username and password combination !");
                    return View();
                }
            }
            else
            {
                //If model state is not valid, the model with error message is returned to the View.
                return View(model);
            }
        }

        //function to check if User is valid or not
        public UsuarioViewModel IsValidUser(LoginViewModel model)
        {
            return _mapper.Map<Usuario, UsuarioViewModel>(_service.LoginValido(model.Email, model.Password));
        }

        public ActionResult Logout()
        {
            HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme
            );

            return RedirectToAction("Index", "Conta");
        }
    }
}

poc.AspNet.Core.MVC/Controllers/EventoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using poc.AspNet.Core.Domain.Interfaces.Services;
using poc.AspNet.Core.Ioc.Entities;
using poc.AspNet.Core.MVC.Models;
using System.Collections.ObjectModel;

namespace poc.AspNet.Core.MVC.Controllers
{
    [Authorize]
    public class EventoController : BaseCrudController<Evento, EventoViewModel>
    {
        protected readonly ICalendarioService _calendarioService;
        protected readonly IUsuarioService _usuarioService;
        protected readonly IEventoConfirmacaoService _eventoConfirmacaoService;
        public EventoController(
            IEventoService serviceCrud,
            ICalendarioService calendarioService,
            IUsuarioService usuarioService,
            IEventoConfirmacaoService eventoConfirmacaoService,
            IMapper mapper
        ) : base(serviceCrud, mapper)
        {
            _calendarioService = calendarioService;
            _usuarioService = usuarioService;
            _eventoConfirmacaoService = eventoConfirmacaoService;
        }

        // GET: Equipe/Create
        public override ActionResult Create()
        {
            ViewBag.Calendarios = _calendarioService.BuscarCalendariosDoUsuario(User.Identity.Name);
            ViewBag.Usuarios = new Collection<UsuarioViewModel> { _mapper.Map<Usuario, UsuarioViewModel>(_usuarioService.BuscarDadosDoUsuario(User.Identity.Name)) };
            return View();
        }

        // GET: Equipe/Edit/5
        public override ActionResult Edit(int id)
        {
            ViewBag.Calendarios = _calendarioService.BuscarCalendariosDoUsuario(User.Identity.Name);

            ViewBag.Usuarios = new Collection<UsuarioViewModel> { _mapper.Map<Usuario, UsuarioViewModel>(_usuarioService.BuscarDadosDoUsuario(User.Identity.Name)) };

            return View(_mapper.Map<Evento, EventoViewModel>(_serviceCrud.GetById(id)));
        }

        // GET: Equipe/Details/5
        public override ActionResult Details(int id)
        {
            var evento = _serviceCrud.GetById(id);

            var retorno = _mapper.Map<Evento, EventoViewModel>(evento);

            IEventoService _serv = _serviceCrud as IEventoService;

            retorno.PercentualConfirmacao = _serv.BuscarPercentualConfirmacao(evento);
            return View(retorno);
        }

        // GET: Equipe/Confirmar/5
        public virtual ActionResult Confirmar(int Id)
        {
            _eventoConfirmacaoService.UsuarioConfirmaPresenca(User.Identity.Name, Id);

            return RedirectToAction("Details");
        }
    }
}

poc.AspNet.Core.MVC/Views/Conta/Index.cshtml
@page
@{
    ViewBag.Title = "Index";
}

<div class="jumbotron">
    <h1>
        @Html.Raw("Ops, Faça o login para ver o conteúdo!");
    </h1>

</div>

poc.AspNet.Core.MVC/Views/Conta/Logado.cshtml
@{
    ViewBag.Title = "Logado";
}

    <h2>
        @Html.Raw("Olá, bem vindo! " + ViewBag.DadosUsuario.Nome)
    </h2>

    <p>
        @Html.Raw($"A temperatura em {ViewBag.PrevisaoTempo.Cidade} no momento é de {ViewBag.PrevisaoTempo.Temperatura} °C")
    </p>

    <h3>
        Eventos Organizados
    </h3>

    <table class="table">
        <tr>
            <th>
                Nome
            </th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.DadosUsuario.EventosOrganizados)
        {
            <tr>
                <td>
                    @Html.Raw(item.Nome)
                </td>
                <td>
                    @Html.ActionLink("Ver Eventos", "Index", "Evento")
                </td>
            </tr>
        }

    </table>

    <h2>
        Eventos Confirmados
    </h2>

    <table class="table">
        <tr>
            <th>
                Nome
            </th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.DadosUsuario.Confirmacoes)
        {
            <tr>
                <td>
                    @Html.Raw(item.Nome)
                </td>
                <td>
                    @Html.ActionLink("Ver Eventos", "Index", "Evento", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

poc.AspNet.Core.MVC/Views/Conta/Login.cshtml
@model poc.AspNet.Core.MVC.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LoginViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
                <a class="btn btn-outline-warning" href="@Url.Action("Index","Home")">Cancelar</a>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Criar sua conta", "Register")
</div>

poc.AspNet.Core.MVC/Views/Conta/Register.cshtml
@model poc.AspNet.Core.MVC.Models.UsuarioViewModel

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Setor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Setor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Setor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DDD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DDD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DDD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEquipe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdEquipe, Model.Equipes, "Selecione uma Equipe", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdEquipe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
                <a class="btn btn-outline-warning" href="@Url.Action("Index","Home")">Cancelar</a>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>