poc.AspNet.Core.MVC/Controllers/EquipeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using poc.AspNet.Core.Domain.Interfaces.Services;
using poc.AspNet.Core.Ioc.Entities;
using poc.AspNet.Core.MVC.Models;

namespace poc.AspNet.Core.MVC.Controllers
{
    [Authorize]
    public class EquipeController : BaseCrudController<Equipe, EquipeViewModel>
    {
        public EquipeController(IEquipeService serviceCrud, IMapper mapper) : base(serviceCrud, mapper)
        {
        }
    }
}

poc.AspNet.Core.MVC/Controllers/UsuarioController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using poc.AspNet.Core.Domain.Interfaces.Services;
using poc.AspNet.Core.Ioc.Entities;
using poc.AspNet.Core.MVC.Models;
using System.Collections.ObjectModel;

namespace poc.AspNet.Core.MVC.Controllers
{
    [Authorize]
    public class UsuarioController : BaseCrudController<Usuario, UsuarioViewModel>
    {
        public UsuarioController(IUsuarioService serviceCrud, IMapper mapper) : base(serviceCrud, mapper)
        {
        }

        private Usuario BuscarDadosUsuarioLogado()
        {
            IUsuarioService _serv = _serviceCrud as IUsuarioService;

            return _serv.BuscarDadosDoUsuario(User.Identity.Name);
        }

        // GET: Equipe
        public override ActionResult Index()
        {
            var usuario = _mapper.Map<Usuario, UsuarioViewModel>(BuscarDadosUsuarioLogado());

            return View("Index", new Collection<UsuarioViewModel> { usuario });
        }

        // GET: Equipe/Create
        public override ActionResult Create()
        {
            var usuario = BuscarDadosUsuarioLogado();

            ViewBag.Equipes = new Collection<EquipeViewModel> { _mapper.Map<Equipe, EquipeViewModel>(usuario.Equipe) };
            return View();
        }

        // GET: Equipe/Edit/5
        public override ActionResult Edit(int id)
        {
            var usuario = BuscarDadosUsuarioLogado();

            ViewBag.Equipes = new Collection<EquipeViewModel> { _mapper.Map<Equipe, EquipeViewModel>(usuario.Equipe) };

            return View(_mapper.Map<Usuario, UsuarioViewModel>(_serviceCrud.GetById(id)));
        }
    }
}

poc.AspNet.Core.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - poc.AspNet.Core.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">poc.AspNet.Core.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Conta" asp-page="/Index">Home</a>
                        </li>

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>
                                @Html.ActionLink("Login", "Login", "Conta")
                            </li>
                            <li>
                                @Html.ActionLink("Registrar", "Register", "Conta")
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Usuarios", "Index", "Usuario")</li>
                            <li>@Html.ActionLink("Equipes", "Index", "Equipe")</li>
                            <li>@Html.ActionLink("Calendario", "Index", "Calendario")</li>
                            <li>@Html.ActionLink("Evento", "Index", "Evento")</li>
                            <li>
                                @Html.ActionLink("Log Out", "Logout", "Conta")
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - poc.AspNet.Core.MVC - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>